import type { SurahSummary } from "@/types";

export const JUZ_AMMA_SURAHS: readonly SurahSummary[] = [
  {
    number: 78,
    arabic: "النَّبَأ",
    transliteration: "An-Naba",
    meaning: "The Tidings",
    verseCount: 40,
    revelation: "Meccan",
  },
  {
    number: 79,
    arabic: "النَّازِعَات",
    transliteration: "An-Nāzi'āt",
    meaning: "Those Who Pull Out",
    verseCount: 46,
    revelation: "Meccan",
  },
  {
    number: 80,
    arabic: "عَبَسَ",
    transliteration: "ʿAbasa",
    meaning: "He Frowned",
    verseCount: 42,
    revelation: "Meccan",
  },
  {
    number: 81,
    arabic: "التَّكْوِير",
    transliteration: "At-Takwīr",
    meaning: "The Folding Up",
    verseCount: 29,
    revelation: "Meccan",
  },
  {
    number: 82,
    arabic: "الانْفِطَار",
    transliteration: "Al-Infiṭār",
    meaning: "The Cleaving",
    verseCount: 19,
    revelation: "Meccan",
  },
  {
    number: 83,
    arabic: "المُطَفِّفِين",
    transliteration: "Al-Muṭaffifīn",
    meaning: "The Defrauders",
    verseCount: 36,
    revelation: "Meccan",
  },
  {
    number: 84,
    arabic: "الانْشِقَاق",
    transliteration: "Al-Inshiqāq",
    meaning: "The Splitting Open",
    verseCount: 25,
    revelation: "Meccan",
  },
  {
    number: 85,
    arabic: "البُرُوج",
    transliteration: "Al-Burūj",
    meaning: "The Constellations",
    verseCount: 22,
    revelation: "Meccan",
  },
  {
    number: 86,
    arabic: "الطَّارِق",
    transliteration: "Aṭ-Ṭāriq",
    meaning: "The Night-Comer",
    verseCount: 17,
    revelation: "Meccan",
  },
  {
    number: 87,
    arabic: "الأَعْلَى",
    transliteration: "Al-A'lā",
    meaning: "The Most High",
    verseCount: 19,
    revelation: "Meccan",
  },
  {
    number: 88,
    arabic: "الغَاشِيَة",
    transliteration: "Al-Ghāshiyah",
    meaning: "The Overwhelming",
    verseCount: 26,
    revelation: "Meccan",
  },
  {
    number: 89,
    arabic: "الفَجْر",
    transliteration: "Al-Fajr",
    meaning: "The Dawn",
    verseCount: 30,
    revelation: "Meccan",
  },
  {
    number: 90,
    arabic: "البَلَد",
    transliteration: "Al-Balad",
    meaning: "The City",
    verseCount: 20,
    revelation: "Meccan",
  },
  {
    number: 91,
    arabic: "الشَّمْس",
    transliteration: "Ash-Shams",
    meaning: "The Sun",
    verseCount: 15,
    revelation: "Meccan",
  },
  {
    number: 92,
    arabic: "اللَّيْل",
    transliteration: "Al-Layl",
    meaning: "The Night",
    verseCount: 21,
    revelation: "Meccan",
  },
  {
    number: 93,
    arabic: "الضُّحَى",
    transliteration: "Aḍ-Ḍuḥā",
    meaning: "The Forenoon",
    verseCount: 11,
    revelation: "Meccan",
  },
  {
    number: 94,
    arabic: "الشَّرْح",
    transliteration: "Ash-Sharḥ",
    meaning: "The Expansion",
    verseCount: 8,
    revelation: "Meccan",
  },
  {
    number: 95,
    arabic: "التِّين",
    transliteration: "At-Tīn",
    meaning: "The Fig",
    verseCount: 8,
    revelation: "Meccan",
  },
  {
    number: 96,
    arabic: "العَلَق",
    transliteration: "Al-'Alaq",
    meaning: "The Clinging Clot",
    verseCount: 19,
    revelation: "Meccan",
  },
  {
    number: 97,
    arabic: "القَدْر",
    transliteration: "Al-Qadr",
    meaning: "The Decree",
    verseCount: 5,
    revelation: "Meccan",
  },
  {
    number: 98,
    arabic: "البَيِّنَة",
    transliteration: "Al-Bayyinah",
    meaning: "The Evidence",
    verseCount: 8,
    revelation: "Medinan",
  },
  {
    number: 99,
    arabic: "الزَّلْزَلَة",
    transliteration: "Az-Zalzalah",
    meaning: "The Earthquake",
    verseCount: 8,
    revelation: "Medinan",
  },
  {
    number: 100,
    arabic: "العَادِيَات",
    transliteration: "Al-'Ādiyāt",
    meaning: "The Chargers",
    verseCount: 11,
    revelation: "Meccan",
  },
  {
    number: 101,
    arabic: "القَارِعَة",
    transliteration: "Al-Qāri'ah",
    meaning: "The Calamity",
    verseCount: 11,
    revelation: "Meccan",
  },
  {
    number: 102,
    arabic: "التَّكَاثُر",
    transliteration: "At-Takāthur",
    meaning: "Rivalry in Increase",
    verseCount: 8,
    revelation: "Meccan",
  },
  {
    number: 103,
    arabic: "العَصْر",
    transliteration: "Al-'Aṣr",
    meaning: "The Time",
    verseCount: 3,
    revelation: "Meccan",
  },
  {
    number: 104,
    arabic: "الهُمَزَة",
    transliteration: "Al-Humazah",
    meaning: "The Slanderer",
    verseCount: 9,
    revelation: "Meccan",
  },
  {
    number: 105,
    arabic: "الفِيل",
    transliteration: "Al-Fīl",
    meaning: "The Elephant",
    verseCount: 5,
    revelation: "Meccan",
  },
  {
    number: 106,
    arabic: "قُرَيْش",
    transliteration: "Quraysh",
    meaning: "Quraysh",
    verseCount: 4,
    revelation: "Meccan",
  },
  {
    number: 107,
    arabic: "المَاعُون",
    transliteration: "Al-Mā'ūn",
    meaning: "Small Kindnesses",
    verseCount: 7,
    revelation: "Meccan",
  },
  {
    number: 108,
    arabic: "الكَوْثَر",
    transliteration: "Al-Kawthar",
    meaning: "Abundance",
    verseCount: 3,
    revelation: "Meccan",
  },
  {
    number: 109,
    arabic: "الكَافِرُون",
    transliteration: "Al-Kāfirūn",
    meaning: "The Disbelievers",
    verseCount: 6,
    revelation: "Meccan",
  },
  {
    number: 110,
    arabic: "النَّصْر",
    transliteration: "An-Naṣr",
    meaning: "The Help",
    verseCount: 3,
    revelation: "Medinan",
  },
  {
    number: 111,
    arabic: "المَسَد",
    transliteration: "Al-Masad",
    meaning: "The Palm-Fibre",
    verseCount: 5,
    revelation: "Meccan",
  },
  {
    number: 112,
    arabic: "الإِخْلَاص",
    transliteration: "Al-Ikhlāṣ",
    meaning: "Sincerity",
    verseCount: 4,
    revelation: "Meccan",
  },
  {
    number: 113,
    arabic: "الفَلَق",
    transliteration: "Al-Falaq",
    meaning: "The Daybreak",
    verseCount: 5,
    revelation: "Meccan",
  },
  {
    number: 114,
    arabic: "النَّاس",
    transliteration: "An-Nās",
    meaning: "Mankind",
    verseCount: 6,
    revelation: "Meccan",
  },
];

export const DEFAULT_SURAH_NUMBER = 93;

export function findSurahSummary(number: number): SurahSummary | undefined {
  return JUZ_AMMA_SURAHS.find((s) => s.number === number);
}
