import type { ComponentType } from "react";

import {
  AdjustIcon,
  AlertInfoIcon,
  AlertWarnIcon,
  AlignLeftIcon,
  ArrowRightIcon,
  ArticleIcon,
  BellIcon,
  BoldIcon,
  BookIcon,
  BookmarkIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ColumnsIcon,
  CompassIcon,
  CopyIcon,
  DownloadIcon,
  ExternalIcon,
  EyeIcon,
  FilterIcon,
  FolderIcon,
  GridIcon,
  Heading1Icon,
  Heading2Icon,
  HeadphonesIcon,
  type IconName,
  type IconProps,
  InsertIcon,
  ItalicIcon,
  LayersIcon,
  LibraryIcon,
  LinkIcon,
  ListIcon,
  LockIcon,
  MapIcon,
  MoonIcon,
  MoreIcon,
  NoteIcon,
  PauseIcon,
  PenIcon,
  PlayIcon,
  PlusIcon,
  QuestionIcon,
  QuoteIcon,
  ReflectIcon,
  SaveIcon,
  SearchIcon,
  SendIcon,
  SettingsIcon,
  ShareIcon,
  ShieldIcon,
  SidebarIcon,
  SourceIcon,
  SparkleIcon,
  StopIcon,
  SunIcon,
  TableIcon,
  TagIcon,
  TimeIcon,
  TypeIcon,
  VideoIcon,
  WandIcon,
  XIcon,
} from "./index";

// IconName → component map. Single source of truth shared by registries
// (slash commands, templates) so the catalog of available icons stays in
// sync without component-level duplication.
export const ICON_MAP: Readonly<Record<IconName, ComponentType<IconProps>>> = {
  book: BookIcon,
  sparkle: SparkleIcon,
  pen: PenIcon,
  library: LibraryIcon,
  compass: CompassIcon,
  source: SourceIcon,
  settings: SettingsIcon,
  search: SearchIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-left": ChevronLeftIcon,
  sidebar: SidebarIcon,
  x: XIcon,
  plus: PlusIcon,
  check: CheckIcon,
  play: PlayIcon,
  pause: PauseIcon,
  bookmark: BookmarkIcon,
  save: SaveIcon,
  copy: CopyIcon,
  link: LinkIcon,
  external: ExternalIcon,
  "alert-warn": AlertWarnIcon,
  "alert-info": AlertInfoIcon,
  sun: SunIcon,
  moon: MoonIcon,
  type: TypeIcon,
  "heading-1": Heading1Icon,
  "heading-2": Heading2Icon,
  bold: BoldIcon,
  italic: ItalicIcon,
  quote: QuoteIcon,
  tag: TagIcon,
  folder: FolderIcon,
  filter: FilterIcon,
  grid: GridIcon,
  list: ListIcon,
  headphones: HeadphonesIcon,
  video: VideoIcon,
  article: ArticleIcon,
  "arrow-right": ArrowRightIcon,
  reflect: ReflectIcon,
  shield: ShieldIcon,
  eye: EyeIcon,
  note: NoteIcon,
  wand: WandIcon,
  insert: InsertIcon,
  table: TableIcon,
  more: MoreIcon,
  send: SendIcon,
  stop: StopIcon,
  adjust: AdjustIcon,
  question: QuestionIcon,
  time: TimeIcon,
  layers: LayersIcon,
  columns: ColumnsIcon,
  "align-left": AlignLeftIcon,
  bell: BellIcon,
  lock: LockIcon,
  download: DownloadIcon,
  share: ShareIcon,
  map: MapIcon,
};

// `IconName` is a string literal union; this guard returns a typed
// component when the name is recognised, `null` otherwise. Avoids forcing
// callers to `as IconName` on user input.
function isIconName(value: string): value is IconName {
  return Object.prototype.hasOwnProperty.call(ICON_MAP, value);
}

export function getIcon(name: string): ComponentType<IconProps> | null {
  if (!isIconName(name)) return null;
  return ICON_MAP[name];
}
